blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

from rest_framework_jwt.views import obtain_jwt_token

from .views import homeView,contactView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',homeView,name='home'),
    path('contact/',contactView,name='contact'),
    path('posts/', include('posts.urls',namespace='posts')),
    path('comments/', include('comments.urls',namespace='comments')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('api/auth/token', obtain_jwt_token),
    path('api/posts/', include('posts.api.urls',namespace='posts-api')),
    path('api/comments/', include('comments.api.urls',namespace='comments-api')),
    path('api/accounts/', include('accounts.api.urls',namespace='accounts-api')),

]
if settings.DEBUG:
    urlpatterns=urlpatterns+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns=urlpatterns+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

from .views import PostListView,PostDetailView,PostCreateView,PostUpdateView,PostDeleteView
app_name='posts'
urlpatterns = [
    path('', PostListView.as_view(),name='list'),
    path('create/', PostCreateView.as_view(),name='create'),
    path('<slug:slug>/',PostDetailView.as_view(),name='detail'),
    path('<slug:slug>/update/', PostUpdateView.as_view(),name='update'),
    path('<slug:slug>/delete/', PostDeleteView.as_view(),name='delete'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <title>Find Pagnn</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% include 'defaults/css.html' %}
    {% block head_extra %}{% endblock head_extra %}
  </head>
  <body style='min-height: 800px;'>
    <div class='container'>
      {% include 'nav.html' %}
      {% block content %}
      {% endblock content %}
      {% include 'footer.html' %}
    </div>
    {% include 'defaults/js.html' %}
  </body>
</html>

templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class='row'>
	<div class='col-12 col-md-8 col-md-offset-2 mx-auto'>
<h3>About</h3>
<p>Hi! My name is Kaiyue Wei (aka Pagnn elsewhere).</p>
<blockquote class="blockquote">
  <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
  <footer class="blockquote-footer">Someone famous in <cite title="Source Title">Source Title</cite></footer>
</blockquote>
<p>Love its people, but never trust its government. Believe in evolution rather than revolution.</p>
</div>
	<div class='col-12 col-md-8 col-md-offset-2 mx-auto'>
<h3>Contact</h3>
I am currently living in Koshigaya, Japan

You can reach me by

Twitter
me@lepture.com
</div>
	<div class='col-12 col-md-8 col-md-offset-2 mx-auto'>
<h3>Projects</h3>
All open source can be found on GitHub, and they are all under BSD License, except that I have declared it under another License.
</div>
	<div class='col-12 col-md-8 col-md-offset-2 mx-auto'>
<h3>Photography</h3>
I take photos in daily life. Find them on Instagram or Flickr.
</div>
</div>
</div>
{% endblock content %}

templates/footer.html
<div class='row text-center my-5'>
	<div class='col-12 col-md-4 mx-auto'>
		<a  href="{% url 'home' %}" style='color:#9ea0a6;'>Find Pagnn</a>
	</div>
	<div class='col-12 col-md-4'>
		
	</div>
	<div class='col-12 col-md-4 mx-auto'>
		<a  href="{% url 'posts:list' %}" style='color:#9ea0a6;'>Archive</a>
	</div>
</div>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% include 'info.html' %}
{% endblock content %}

templates/info.html
{% load static %}
<div class='row my-5'>
  <div class='col-md-8 col-md-offset-2 mx-auto'>
    <div class='row'>
      <div class='col-2 col-offset-1'>
        <img src="{% static 'img/pagnn.jpg' %}" class='img-fluid' style='border-radius: 50%;' >
      </div>
  <div class='info col-8'>
<h3 >Pagnn</h3>

  <a href="https://github.com/pagnn">
  <i class="fa fa-github" aria-hidden="true"></i>
  </a>
  <a href="https://twitter.com/pagnn">
  <i class="fa fa-twitter" aria-hidden="Twitter"></i>
</a>
</div>
</div>
</div>
</div>

templates/nav.html
{% url 'contact' as contact_url %}
{% url 'about' as about_url %}
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-white">
  <a class="navbar-brand" href="{% url 'home' %}" style='color:#9ea0a6;'>Find Pagnn</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
        <a class="nav-link " href="{{ contact_url }}">Contact<span class="sr-only">(current)</span></a>
      </li>
    </ul>
  </div>
</nav>